// programsData.js — Learning programs for Deckstack

const programsData = [
  {
    id: 'social-confidence',
    title: 'Social Confidence Foundations',
    description: 'Build the core skills for confident, calm communication — from handling criticism and pressure to starting conversations and connecting with people.',
    icon: 'ti-messages',
    sections: [
      {
        id: 'section-1',
        title: 'Section 1 — Holding Your Ground',
        packs: [
          { key: 'assertive', label: 'Assertive Communication' },
        ],
        checkpoint: {
          id: 'social-confidence-cp1',
          title: 'Checkpoint — Section 1',
          timeLimit: 90,
          drawCount: 20,
          questions: [
            // FOGGING (8 questions)
            { id: 'f1', q: 'What is the core idea behind Fogging?', options: ['Agreeing with what might be true in criticism, without defending yourself','Deflecting criticism with a counter-argument','Apologising quickly to end the conflict','Asking the critic to prove their point'], correct: 0 },
            { id: 'f2', q: 'Someone says you are too sensitive. A good Fogging response is:', options: ['"I am not sensitive at all."','"You could have a point there."','"Why would you say something like that?"','"That is really hurtful."'], correct: 1 },
            { id: 'f3', q: 'Why does Fogging work as a technique?', options: ['It makes the critic feel guilty','It shows you agree with everything they say','Criticism has nothing solid to grip onto — it passes through like fog','It forces the other person to explain themselves'], correct: 2 },
            { id: 'f4', q: 'Which of these is a Fogging response?', options: ['"I completely disagree with that."','"You might be right about that."','"Let me explain why I did it."','"That is not fair."'], correct: 1 },
            { id: 'f5', q: 'Fogging involves agreeing with:', options: ['Everything the critic says','Nothing — the goal is silence','What might be true, the possibility, or the logic of the criticism','Only facts, never opinions'], correct: 2 },
            { id: 'f6', q: 'Someone criticises your driving. The best Fogging response is:', options: ['"I am a perfectly good driver."','"You might be right about that."','"Maybe you should drive then."','"Why are you always criticising me?"'], correct: 1 },
            { id: 'f7', q: 'What does Fogging signal to the other person?', options: ['That you are angry but staying calm','That you agree with everything they said','Confidence and unshakeable calm','That you want to end the conversation'], correct: 2 },
            { id: 'f8', q: 'Which phrase best demonstrates Fogging?', options: ['"I can see why you think so."','"You are wrong about that."','"I will try harder."','"Stop criticising me."'], correct: 0 },
            // NEGATIVE INQUIRY (5 questions)
            { id: 'ni1', q: 'What is the goal of Negative Inquiry?', options: ['To make the other person feel bad','To calmly ask for more criticism to disarm and clarify','To end the conversation quickly','To agree with everything said'], correct: 1 },
            { id: 'ni2', q: 'Someone says you are being difficult. A Negative Inquiry response is:', options: ['"I am not being difficult."','"Fine, I will do it your way."','"What is it specifically that I am doing that feels difficult?"','"You are the one being difficult."'], correct: 2 },
            { id: 'ni3', q: 'Negative Inquiry works because:', options: ['It is hard to keep attacking someone who is genuinely listening','It shows the critic that you are right','It forces the critic to apologise','It gives you time to think of a counter-argument'], correct: 0 },
            { id: 'ni4', q: 'Someone gives you vague criticism. The best Negative Inquiry response is:', options: ['"That is not a fair criticism."','"What do you mean exactly? I would like to understand."','"Why do you always criticise me?"','"I will think about it."'], correct: 1 },
            { id: 'ni5', q: 'What does using Negative Inquiry demonstrate?', options: ['That you are afraid of the critic','That you are not afraid of more criticism','That you agree with the criticism','That you want to change the subject'], correct: 1 },
            // NEGATIVE ASSERTION (6 questions)
            { id: 'na1', q: 'Negative Assertion means:', options: ['Denying your faults calmly','Actively and calmly agreeing with your own faults when pointed out','Apologising extensively when you make a mistake','Explaining why you made a mistake'], correct: 1 },
            { id: 'na2', q: 'Someone says your joke was not funny. The best Negative Assertion response is:', options: ['"I thought it was funny."','"Sorry, I did not mean to offend."','"No, that one did not land."','"You just do not have a sense of humour."'], correct: 2 },
            { id: 'na3', q: 'The key principle behind Negative Assertion is:', options: ['Explain your mistakes fully','Acknowledge without shrinking','Apologise quickly and move on','Deny minor faults to maintain confidence'], correct: 1 },
            { id: 'na4', q: 'Someone points out you were late. A good Negative Assertion response is:', options: ['"The traffic was terrible."','"I am so sorry, it will never happen again."','"You are right, I was late. That is on me."','"I was only five minutes late."'], correct: 2 },
            { id: 'na5', q: 'Which of these is NOT a Negative Assertion response?', options: ['"You are right, I could have done that differently."','"Yes, that was a mistake. I will fix it."','"No, that one did not land."','"I did not do anything wrong."'], correct: 3 },
            { id: 'na6', q: 'Negative Assertion communicates:', options: ['That you are weak','That you can be wrong and still be okay — acknowledging shows strength','That you are trying to end the conversation','That you are hiding anger'], correct: 1 },
            // BROKEN RECORD (6 questions)
            { id: 'br1', q: 'Broken Record means:', options: ['Repeating a long explanation until understood','Returning to the same calm, short response every time the other person pushes','Raising your voice gradually to show seriousness','Listing all the reasons behind your decision'], correct: 1 },
            { id: 'br2', q: 'Why should you avoid explaining yourself when using Broken Record?', options: ['Explanations make you sound uncertain','Every explanation gives the other person a new argument to counter','Explanations take too long','The other person will not listen anyway'], correct: 1 },
            { id: 'br3', q: 'A salesperson will not take no for an answer. The best Broken Record response is:', options: ['"I already said no, please stop."','"Let me think about it."','"That does not work for me." — repeated calmly.','"I need to speak to my partner first."'], correct: 2 },
            { id: 'br4', q: 'When someone escalates pressure, you should:', options: ['Match their energy','Apologise and reconsider','Hold the same calm tone — that is exactly when the technique is tested','Change your wording to try a different approach'], correct: 2 },
            { id: 'br5', q: 'Which correctly uses Broken Record?', options: ['Repeating different reasons each time','Repeating the same calm sentence without changing the wording','Gradually giving in to reduce conflict','Asking why they keep pushing'], correct: 1 },
            { id: 'br6', q: 'The mindset behind Broken Record is:', options: ['"I need to justify my boundaries."','"I do not need to justify my boundaries. Repeating myself is stable, not strange."','"If I repeat myself, people think I am not listening."','"I should only say no once, then give in gracefully."'], correct: 1 },
            // GENERAL (6 questions)
            { id: 'g1', q: 'Which technique is best when someone keeps pushing after you said no?', options: ['Fogging','Negative Assertion','Broken Record','Negative Inquiry'], correct: 2 },
            { id: 'g2', q: 'Which technique is best for vague or unclear criticism?', options: ['Broken Record','Negative Inquiry','Fogging','Negative Assertion'], correct: 1 },
            { id: 'g3', q: 'Which technique is best when someone points out a mistake you genuinely made?', options: ['Fogging','Negative Inquiry','Broken Record','Negative Assertion'], correct: 3 },
            { id: 'g4', q: 'Which technique is best when someone criticises you and you want to stay calm without engaging?', options: ['Broken Record','Negative Assertion','Fogging','Negative Inquiry'], correct: 2 },
            { id: 'g5', q: 'All four techniques share one thing. What is it?', options: ['They all involve apologising','They all involve staying calm and not getting defensive','They all require the other person to back down','They all involve explaining your reasoning'], correct: 1 },
            { id: 'g6', q: 'Someone says "you never listen." Which technique lets you acknowledge without defending?', options: ['Broken Record','Negative Assertion','Fogging','Negative Inquiry'], correct: 2 },
          ],
        },
      },
      {
        id: 'section-2',
        title: 'Section 2 — Starting & Deepening Conversations',
        packs: [
          { key: 'startingconnecting', label: 'Starting & Connecting' },
          { key: 'conversationaldepth', label: 'Conversational Depth' },
        ],
        checkpoint: {
          id: 'social-confidence-cp2',
          title: 'Checkpoint — Section 2',
          timeLimit: 90,
          drawCount: 20,
          questions: [
            // STARTING & CONNECTING (15 questions)
            { id: 'sc1', q: 'What is the most effective opener when meeting someone new?', options: ['A clever or witty line','An observation about the shared situation or environment','A question about their job or status','A compliment about their appearance'], correct: 1 },
            { id: 'sc2', q: 'Small talk serves what purpose?', options: ['Wasting time before the real conversation','Building a bridge of comfort that allows deeper conversation','Showing that you are interesting','Testing whether someone is worth talking to'], correct: 1 },
            { id: 'sc3', q: 'Someone looks uncomfortable in a group setting. A good opening is:', options: ['"You look like you are not enjoying yourself."','"Do you know many people here?"','"Why are you standing alone?"','"This is a great party, right?"'], correct: 1 },
            { id: 'sc4', q: 'What does a good follow-up question do?', options: ['Changes the subject to something more interesting','Shows you heard and are curious about what they just said','Demonstrates your own knowledge on the topic','Returns the conversation to you'], correct: 1 },
            { id: 'sc5', q: 'When a conversation stalls, the best move is:', options: ['End the conversation politely','Add an observation or share something briefly about yourself that links to their topic','Ask them what they want to talk about','Wait for them to restart it'], correct: 1 },
            { id: 'sc6', q: 'The "free information" principle means:', options: ['You should only share information when asked','People offer extra detail in their answers — follow those threads','Small talk should be kept impersonal','Information is currency and should be rationed'], correct: 1 },
            { id: 'sc7', q: 'You are at an event and want to approach someone standing alone. The best approach is:', options: ['Wait until they approach you','Walk over, make eye contact, and comment on something in the shared context','Send a message via a mutual friend','Open with a direct question about them'], correct: 1 },
            { id: 'sc8', q: 'Which of these is the weakest conversation opener?', options: ['"Have you been here before?"','"How do you know the host?"','"So, what do you do?"','"What brought you to this event?"'], correct: 2 },
            { id: 'sc9', q: 'Active listening in conversation means:', options: ['Staying quiet until it is your turn to speak','Nodding while thinking about what to say next','Showing through questions and responses that you are genuinely tracking what they say','Repeating back exactly what someone said'], correct: 2 },
            { id: 'sc10', q: 'A conversation is going well when:', options: ['You are doing most of the talking','Both people are sharing and building on what the other says','The other person keeps asking you questions','You avoid any silences'], correct: 1 },
            { id: 'sc11', q: 'What is the risk of filling every silence in a conversation?', options: ['The other person thinks you are boring','You prevent the natural rhythm that allows the other person to open up','Silences are never appropriate in conversation','The conversation becomes too slow'], correct: 1 },
            { id: 'sc12', q: 'Self-disclosure in conversation means:', options: ['Sharing your opinion on controversial topics','Sharing something personal to create reciprocity and depth','Telling people about your achievements','Disclosing information the other person asked for'], correct: 1 },
            { id: 'sc13', q: 'When you share something personal, what often happens?', options: ['The other person feels uncomfortable','The other person is more likely to share something personal in return','The conversation becomes too serious','The other person loses interest'], correct: 1 },
            { id: 'sc14', q: 'Ending a conversation well means:', options: ['Excusing yourself as soon as you want to leave','Leaving the other person feeling good about the interaction — a warm close','Waiting for them to end it','Summarising everything you discussed'], correct: 1 },
            { id: 'sc15', q: 'What separates a forgettable conversation from a memorable one?', options: ['The topics covered','The amount of information exchanged','Whether both people felt genuinely seen and heard','How long the conversation lasted'], correct: 2 },
            // CONVERSATIONAL DEPTH (15 questions)
            { id: 'cd1', q: 'Conversational depth means:', options: ['Talking about intellectual or academic subjects','Moving from surface topics to what genuinely matters to the other person','Asking many questions in a row','Keeping the conversation going as long as possible'], correct: 1 },
            { id: 'cd2', q: 'A good deep question has which quality?', options: ['It has a clear right or wrong answer','It invites reflection and a personal response — not just facts','It is unexpected and unusual','It makes the other person think for a long time'], correct: 1 },
            { id: 'cd3', q: 'Someone says they have been travelling. A surface response is "where did you go?" A deeper response might be:', options: ['"How long were you away?"','"What surprised you most about being there?"','"Was it expensive?"','"Did you go alone?"'], correct: 1 },
            { id: 'cd4', q: 'What is the purpose of vulnerability in conversation?', options: ['To make the other person feel sorry for you','To signal that the conversation is a safe space for honesty','To demonstrate emotional intelligence','To move the conversation onto personal topics quickly'], correct: 1 },
            { id: 'cd5', q: 'You share something honest and slightly vulnerable. What often happens next?', options: ['The other person becomes uncomfortable','The other person is more likely to share something honest in return','The conversation shifts to advice-giving','The other person takes over the conversation'], correct: 1 },
            { id: 'cd6', q: 'The best moment to move a conversation deeper is:', options: ['At the very start, before small talk','When there is a natural pause and both people seem comfortable','After 20 minutes of conversation regardless of feel','When the other person asks a deep question'], correct: 1 },
            { id: 'cd7', q: 'Someone says "I have been pretty stressed lately." A depth-building response is:', options: ['"That sounds tough."','"Have you tried meditation?"','"What is it that has been weighing on you most?"','"Stress is so common these days."'], correct: 2 },
            { id: 'cd8', q: 'What kills conversational depth most quickly?', options: ['Talking about yourself too much','Giving advice before the person feels fully heard','Asking too many questions','Sharing your own opinion'], correct: 1 },
            { id: 'cd9', q: 'The phrase "tell me more about that" works because:', options: ['It shows you have a large vocabulary','It is open-ended and gives the person space to go wherever matters most to them','It makes the other person feel intelligent','It buys you time to think of a better question'], correct: 1 },
            { id: 'cd10', q: 'Which is the deeper version of the same question?', options: ['"What is your job?" vs "What do you do for fun?"','"Where are you from?" vs "What was it like growing up there?"','"How long have you been friends?" vs "When did you meet?"','"Do you like your job?" vs "What do you do?"'], correct: 1 },
            { id: 'cd11', q: 'Emotional attunement in conversation means:', options: ['Matching the energy and emotional tone of what the other person is experiencing','Sharing your own emotions whenever relevant','Staying calm regardless of the topic','Asking how someone is feeling directly'], correct: 0 },
            { id: 'cd12', q: 'Someone shares something painful. Before offering a reframe or advice, you should:', options: ['Ask clarifying questions','Make sure they feel fully heard and acknowledged','Share a similar experience of your own','Offer a solution'], correct: 1 },
            { id: 'cd13', q: 'What is the difference between sympathy and empathy in conversation?', options: ['Sympathy is stronger than empathy','Empathy joins someone in their experience; sympathy looks at it from the outside','Sympathy requires physical presence; empathy does not','There is no meaningful difference'], correct: 1 },
            { id: 'cd14', q: 'A good question for building depth does NOT:', options: ['Invite personal reflection','Have a yes or no answer','Relate to what the person just shared','Give the person room to decide how much to share'], correct: 1 },
            { id: 'cd15', q: 'The best conversations tend to end with both people feeling:', options: ['Informed about each other','Tired from thinking deeply','Seen, heard, and genuinely curious about talking again','Satisfied that they covered all the important topics'], correct: 2 },
          ],
        },
      },
    ],
  },,

  {
    id: 'conversation-skills',
    title: 'Conversation Skills Foundations',
    description: 'Learn how to start conversations with confidence, keep them going, and create genuine connection — from small talk to meaningful depth.',
    icon: 'ti-message-circle',
    sections: [
      {
        id: 'section-1',
        title: 'Section 1 — Starting & Connecting',
        packs: [
          { key: 'startingconnecting', label: 'Starting & Connecting' },
        ],
        checkpoint: {
          id: 'conversation-skills-cp1',
          title: 'Checkpoint — Section 1',
          timeLimit: 90,
          drawCount: 20,
          questions: [
            { id: 'cs1', q: 'What is the most effective opener when meeting someone new?', options: ['A clever or witty line','An observation about the shared situation or environment','A question about their job','A compliment about their appearance'], correct: 1 },
            { id: 'cs2', q: 'Small talk serves what purpose?', options: ['Wasting time before the real conversation','Building a bridge of comfort that allows deeper conversation','Showing you are interesting','Testing whether someone is worth talking to'], correct: 1 },
            { id: 'cs3', q: 'What does a good follow-up question do?', options: ['Changes the subject','Shows you heard and are curious about what they just said','Demonstrates your knowledge','Returns the conversation to you'], correct: 1 },
            { id: 'cs4', q: 'The "free information" principle means:', options: ['You should only share when asked','People offer extra detail in answers — follow those threads','Small talk should stay impersonal','Information should be rationed'], correct: 1 },
            { id: 'cs5', q: 'Which of these is the weakest conversation opener?', options: ['"Have you been here before?"','"How do you know the host?"','"So, what do you do?"','"What brought you here today?"'], correct: 2 },
            { id: 'cs6', q: 'When a conversation stalls, the best move is:', options: ['End it politely','Add an observation or share something that links to their topic','Ask what they want to talk about','Wait for them to restart'], correct: 1 },
            { id: 'cs7', q: 'Active listening means:', options: ['Staying quiet until your turn','Nodding while thinking of what to say','Showing through questions and responses that you are tracking what they say','Repeating back exactly what was said'], correct: 2 },
            { id: 'cs8', q: 'A conversation is going well when:', options: ['You are doing most of the talking','Both people are sharing and building on what the other says','The other person keeps asking questions','You avoid all silences'], correct: 1 },
            { id: 'cs9', q: 'What is the risk of filling every silence?', options: ['You seem boring','You prevent the natural rhythm that lets the other person open up','Silences are never appropriate','The conversation slows down'], correct: 1 },
            { id: 'cs10', q: 'Self-disclosure means:', options: ['Sharing opinions on controversial topics','Sharing something personal to create reciprocity and depth','Telling people about achievements','Revealing information when asked'], correct: 1 },
            { id: 'cs11', q: 'When you share something personal, what often happens?', options: ['The other person feels uncomfortable','The other person is more likely to share something personal in return','The conversation becomes too serious','The other person loses interest'], correct: 1 },
            { id: 'cs12', q: 'Ending a conversation well means:', options: ['Excusing yourself as soon as you want to leave','Leaving the other person feeling good about the interaction','Waiting for them to end it','Summarising everything discussed'], correct: 1 },
            { id: 'cs13', q: 'You want to approach someone standing alone at an event. The best move is:', options: ['Wait until they approach you','Walk over, make eye contact, comment on something in the shared context','Ask a mutual friend to introduce you','Open with a direct question about them'], correct: 1 },
            { id: 'cs14', q: 'What separates a forgettable conversation from a memorable one?', options: ['The topics covered','The amount of information exchanged','Whether both people felt genuinely seen and heard','How long it lasted'], correct: 2 },
            { id: 'cs15', q: 'A good conversation leaves both people feeling:', options: ['Informed about each other','Tired from thinking','Seen, heard, and curious about talking again','Satisfied they covered everything'], correct: 2 },
            { id: 'cs16', q: 'What does it mean to "follow the thread" in conversation?', options: ['Stay on one topic until it is exhausted','Pick up on the extra detail someone offered and explore it','Keep the conversation moving quickly','Avoid going off-topic'], correct: 1 },
            { id: 'cs17', q: 'Rapport is best described as:', options: ['A formal agreement between two people','A feeling of mutual comfort and ease that makes conversation flow','A technique for getting people to like you','The result of sharing personal information'], correct: 1 },
            { id: 'cs18', q: 'When someone gives a short answer, the best response is:', options: ['Move to a new topic','Share your own view on the subject','Ask a follow-up that invites them to say more','Summarise what they said'], correct: 2 },
            { id: 'cs19', q: 'What role does mirroring energy play in conversation?', options: ['It means copying everything the other person does','Matching the other person’s tone and pace helps them feel comfortable','It is manipulative and should be avoided','It only works in professional settings'], correct: 1 },
            { id: 'cs20', q: 'Why is showing genuine curiosity more effective than memorising openers?', options: ['Memorised lines are always obvious','Curiosity is self-sustaining — it naturally generates questions and follow-ups','Openers are too short to build rapport','People can tell when you are interested'], correct: 1 },
          ],
        },
      },
      {
        id: 'section-2',
        title: 'Section 2 — Going Deeper',
        packs: [
          { key: 'conversationaldepth', label: 'Conversational Depth' },
          { key: 'listeningresponding', label: 'Listening & Responding' },
        ],
        checkpoint: {
          id: 'conversation-skills-cp2',
          title: 'Checkpoint — Section 2',
          timeLimit: 90,
          drawCount: 20,
          questions: [
            { id: 'cd1', q: 'Conversational depth means:', options: ['Talking about intellectual subjects','Moving from surface topics to what genuinely matters to the other person','Asking many questions in a row','Keeping conversation going as long as possible'], correct: 1 },
            { id: 'cd2', q: 'A good deep question:', options: ['Has a clear right or wrong answer','Invites reflection and a personal response — not just facts','Is unexpected and unusual','Makes the other person think for a long time'], correct: 1 },
            { id: 'cd3', q: 'Someone says they have been travelling. A deeper response is:', options: ['"How long were you away?"','"What surprised you most about being there?"','"Was it expensive?"','"Did you go alone?"'], correct: 1 },
            { id: 'cd4', q: 'What is the purpose of vulnerability in conversation?', options: ['To make the other person feel sorry for you','To signal the conversation is a safe space for honesty','To demonstrate emotional intelligence','To move quickly to personal topics'], correct: 1 },
            { id: 'cd5', q: 'When you share something honest and slightly vulnerable, what often follows?', options: ['The other person becomes uncomfortable','The other person is more likely to share something honest in return','The conversation shifts to advice-giving','The other person takes over'], correct: 1 },
            { id: 'cd6', q: 'The best moment to move deeper is:', options: ['At the very start','When there is a natural pause and both people seem comfortable','After exactly 20 minutes','When the other person asks a deep question first'], correct: 1 },
            { id: 'cd7', q: 'Someone says "I have been pretty stressed lately." A depth-building response is:', options: ['"That sounds tough."','"Have you tried meditation?"','"What has been weighing on you most?"','"Stress is so common."'], correct: 2 },
            { id: 'cd8', q: 'What kills conversational depth most quickly?', options: ['Talking about yourself','Giving advice before the person feels fully heard','Asking too many questions','Sharing your opinion'], correct: 1 },
            { id: 'cd9', q: '"Tell me more about that" works because:', options: ['It shows you have a large vocabulary','It is open-ended and gives the person space to go where it matters most','It makes the other person feel intelligent','It buys you time to think'], correct: 1 },
            { id: 'cd10', q: 'Which is the deeper version of the same question?', options: ['"What is your job?" vs "What do you do for fun?"','"Where are you from?" vs "What was it like growing up there?"','"How long have you been friends?" vs "When did you meet?"','"Do you like your job?" vs "What do you do?"'], correct: 1 },
            { id: 'lr1', q: 'Active listening is best described as:', options: ['Staying silent until it is your turn','Preparing your response while they speak','Demonstrating through questions and responses that you are genuinely tracking what is said','Agreeing with everything said'], correct: 2 },
            { id: 'lr2', q: 'Reflective listening means:', options: ['Repeating every word exactly','Showing you understood by responding to the meaning and feeling behind what was said','Asking clarifying questions only','Summarising at the end of each turn'], correct: 1 },
            { id: 'lr3', q: 'Someone shares something painful. Before offering advice you should:', options: ['Ask clarifying questions','Make sure they feel fully heard and acknowledged','Share a similar experience','Offer a solution'], correct: 1 },
            { id: 'lr4', q: 'The difference between empathy and sympathy is:', options: ['Empathy is stronger','Empathy joins someone in their experience; sympathy looks at it from outside','Sympathy requires physical presence','There is no meaningful difference'], correct: 1 },
            { id: 'lr5', q: 'A good listening response does NOT:', options: ['Acknowledge the feeling','Invite them to say more','Immediately shift to your own experience','Reflect back what you heard'], correct: 2 },
            { id: 'lr6', q: 'When someone is talking and you feel the urge to interrupt with advice, you should:', options: ['Interrupt — it shows engagement','Hold it and continue listening until they feel fully heard','Ask if they want advice first','Change the subject once they pause'], correct: 1 },
            { id: 'lr7', q: 'Emotional attunement means:', options: ['Always agreeing with how the other person feels','Matching the energy and emotional tone of what the other person is experiencing','Staying calm regardless of topic','Asking how someone feels directly'], correct: 1 },
            { id: 'lr8', q: 'What does it mean to "hold space" for someone?', options: ['Standing close to them physically','Being fully present without trying to fix, advise or redirect','Keeping the conversation going with questions','Agreeing with everything they say'], correct: 1 },
            { id: 'lr9', q: 'When responding to someone in distress, the most important first step is:', options: ['Offering a solution','Sharing a similar story','Acknowledging what they are feeling without judgement','Asking what they need'], correct: 2 },
            { id: 'lr10', q: 'The best conversations tend to end with both people feeling:', options: ['Informed','Tired from depth','Seen, heard and genuinely curious about talking again','Satisfied they covered all topics'], correct: 2 },
          ],
        },
      },
    ],
  },
];
